<?php

return [
    '/'                 => 'Controllers/home.php',

    '/members'          => 'Controllers/members/index.php',
    '/members/show'     => 'Controllers/members/show.php',
    '/members/create'   => 'Controllers/members/create.php',
    '/members/store'    => 'Controllers/members/store.php',
    '/members/edit'     => 'Controllers/members/edit.php',
    '/members/update'   => 'Controllers/members/update.php',
    '/members/destroy'  => 'Controllers/members/destroy.php',

    '/genres'           => 'Controllers/genres/index.php',
    '/genres/show'      => 'Controllers/genres/show.php',
    '/genres/create'    => 'Controllers/genres/create.php',
    '/genres/store'     => 'Controllers/genres/store.php',
    '/genres/edit'      => 'Controllers/genres/edit.php',
    '/genres/update'    => 'Controllers/genres/update.php',
    '/genres/destroy'   => 'Controllers/genres/destroy.php',

    '/movies'           => 'Controllers/movies/index.php',
    '/movies/show'      => 'Controllers/movies/show.php',
    '/movies/create'    => 'Controllers/movies/create.php',
    '/movies/store'     => 'Controllers/movies/store.php',
    '/movies/edit'      => 'Controllers/movies/edit.php',
    '/movies/update'    => 'Controllers/movies/update.php',
    '/movies/destroy'   => 'Controllers/movies/destroy.php',

    '/prices'           => 'Controllers/prices/index.php',
    '/prices/show'      => 'Controllers/prices/show.php',
    '/prices/create'    => 'Controllers/prices/create.php',
    '/prices/store'     => 'Controllers/prices/store.php',
    '/prices/edit'      => 'Controllers/prices/edit.php',
    '/prices/update'    => 'Controllers/prices/update.php',
    '/prices/destroy'   => 'Controllers/prices/destroy.php',

    '/media'           => 'Controllers/media/index.php',
    '/media/show'      => 'Controllers/media/show.php',
    '/media/create'    => 'Controllers/media/create.php',
    '/media/store'     => 'Controllers/media/store.php',
    '/media/edit'      => 'Controllers/media/edit.php',
    '/media/update'    => 'Controllers/media/update.php',
    '/media/destroy'   => 'Controllers/media/destroy.php',

    '/borrow'           => 'Controllers/borrow/index.php',
    '/borrow/show'      => 'Controllers/borrow/show.php',
    '/borrow/create'    => 'Controllers/borrow/create.php',
    '/borrow/store'     => 'Controllers/borrow/store.php',
    '/borrow/edit'      => 'Controllers/borrow/edit.php',
    '/borrow/update'    => 'Controllers/borrow/update.php',
    '/borrow/destroy'   => 'Controllers/borrow/destroy.php',

    '/dashboard'           => 'Controllers/dashboard/index.php',
    '/dashboard/show'      => 'Controllers/dashboard/show.php',
    '/dashboard/create'    => 'Controllers/dashboard/create.php',
    '/dashboard/store'     => 'Controllers/dashboard/store.php',
    '/dashboard/edit'      => 'Controllers/dashboard/edit.php',
    '/dashboard/update'    => 'Controllers/dashboard/update.php',
    '/dashboard/destroy'   => 'Controllers/dashboard/destroy.php',
];